version: '3.8'

services:
  # Base de Datos SQL: PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: cooperadora-sql-postgres
    restart: always
    environment:
      POSTGRES_DB: cooperadora_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Base de Datos NoSQL: MongoDB
  mongodb:
    image: mongo:latest
    container_name: cooperadora-nosql-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
